export const SYMBOLS = {
  TODO_REPOSITORY: Symbol('TODO_REPOSITORY'),
  TODO_CREATE: Symbol('TODO_CREATE'),
  TODO_LIST: Symbol('TODO_LIST'),
  STORE: Symbol('Store'),
  UUID_GENERATOR: Symbol('UUID_GENERATOR'),
  TODO_COMPLETE_TODO: Symbol('TODO_COMPLETE_TODO'),
};
